name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [add.py]
jobs:
  Explore-GitHub-Actions:
    runs-on: add.py
    
      - run: echo "ğŸ This job's status is ${{ job.status }}."