name: GitHub Actions add
run-name: Bienvenue ${{ github.actor }} sur Github Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execution du fichier Python 
        run: |
          python add.py
      - run: echo "ğŸ l'instruction est ${{ job.status }}."